### ISSUE TITLE
Support using docker secrets for environment variables in docker-compose.yml

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1745]
Users have indicated the desire to set some of the env vars, like `WFM_USER` and `WFM_PASSWORD`, using [docker secrets](https://docs.docker.com/compose/use-secrets/).

Postgres has a [convention](https://stackoverflow.com/a/61622275/1424791) for this. For example, in `docker-compose.yml`:

```yml
environment:
  POSTGRES_USER_FILE: /run/secrets/user
  POSTGRES_PASSWORD_FILE: /run/secrets/pass
  POSTGRES_DB_FILE: /run/secrets/db
```

Can be used instead of:

```yml
environment:
  POSTGRES_USER: mpf
  POSTGRES_PASSWORD: password
  POSTGRES_DB: mpf
```

One approach would be enable any env var to be specified using a file (secret or otherwise) just by providing an `<ENV_VAR_NAME>_FILE` env var.
