### ISSUE TITLE
User prompted to enter passwords during deployment even they did not select the option to provide them

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#574]
This behavior was observed when performing an OpenMPF upgrade after running `sudo yum update -y`. It may be related to how the version of Ansible was updated as part of the process, and how we currently only support an older version of Ansible.

Specifically, the user pressed Enter at the following prompt to select the default answer of N:

```
'Set custom passwords for workflow-manager and MySQL?
```

And then the user was prompted for those passwords anyway. Here's the Python code:

```
# Prompt for password configuration
pwcfg_choice = yes_or_no_prompt('Set custom passwords for workflow-manager and MySQL?', False)

# Set the pwcfg dict
pwcfg = {'change': pwcfg_choice}
```

Later on that variable is passed to Ansible and used in mpf-pwcfg.yml:

```
  vars_prompt:
    - name: "mpf_wfm_pw"
      prompt: "Enter the custom workflow manager mpf user password or press enter for the default value"
      default: "mpf123"
      private: yes
      confirm: yes
      when: pwcfg | bool
```

mpf-pwcfg.yml is included by mpf-site.yml:

```
- include: mpf-pwcfg.yml
  when: pwcfg|bool
```

The "include" may be the problem. When the behavior was observed, Ansible printed a message saying that "include" is deprecated. See [this](https://github.com/geerlingguy/drupal-vm/issues/1553).
