### ISSUE TITLE
Deployment fails if master node is not specified as a child node

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#602]
```
TASK [child : Unregister old MogMotionDetection component] *********************

fatal: [somehost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'admin_wfm_pw' is undefined

The error appears to have been in '/opt/mpf/manage/ansible/roles/child/tasks/compunregistration.yml': line 29, column 3,
```

This seems to be caused by the fact that in the following Ansible task, `admin_wfm_pw` is not defined in /home/mpf/git/openmpf-projects/openmpf/trunk/ansible/install/ansible/roles/child/vars/main.yml. That variable is defined in the flow for the master node, but not child nodes. 

```
- name: "Unregister old {{ item.componentName }} component"
  uri:
    url: "{{ unregister_component_uri }}{{ mpf_home }}/plugins/{{ item.componentDescriptorPath }}&deletePackage=false&recursive=false"
    method: GET
    follow_redirects: all
    force_basic_auth: yes
    user: "admin"
    password: "{{ admin_wfm_pw }}"
    status_code: 200
    return_content: yes
    timeout: 150
    validate_certs: no
  environment:
    no_proxy: "{{ master_host }}"
  run_once: true
  when: can_register_components and item.register and item.componentDescriptorPath
  register: unregistration_results
  failed_when: unregistration_results.status == 404
  delegate_to: "{{ master_host }}"
```

Ansible be be caching that value for that variable when the master node is provided as the first hostname by the user at the following prompt during the deployment process:

```
Provide the hostname of each MPF Child Host. (Press <Enter> after each host, twice when complete):
```
